import { ThemeModeScript } from "flowbite-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeInit } from "../.flowbite-react/init";
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import Navbar from "./components/navbar/Navbar";

import { UserProvider } from "./context/UserProvider";
import { CompanyProvider } from "./context/CompanyProvider";
import { CompanyBranchesProvider } from "./context/CompanyBranchesProvider";
import { UserAccessProvider } from "./context/UserAccessProvider";

import "./globals.css";
import Sidebar from "./(protected)/components/sidebar/Sidebar";
import AppsMenu from "./(protected)/components/apps/Apps";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flowbite React Template Next.js",
  description: "Generated by create-flowbite-react",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createServerComponentClient({ cookies });
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  console.log("🌐 Sesión desde layout:", user);
  console.log("❌ Error desde layout:", error);

  return (
    <UserProvider>
      <CompanyProvider>
        <UserAccessProvider>
          <CompanyBranchesProvider>
            <html lang="es" suppressHydrationWarning>
              <head>
                <ThemeModeScript />
              </head>
              <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
              >
                <ThemeInit />
                <Navbar />

                {children}
              </body>
            </html>
          </CompanyBranchesProvider>
        </UserAccessProvider>
      </CompanyProvider>
    </UserProvider>
  );
}
